"""init

Revision ID: 20b95d1592c9
Revises: 'None'
Create Date: 2025-11-10 13:42:33.423078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b95d1592c9'
down_revision = 'None'
branch_labels = 'None'
depends_on = 'None'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
